project_name: cf-plugin-bg-restage

builds:
  -
    &template
    id: binary
    dir: .
    binary: cf-plugin-bg-restage
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X main.Major={{.Major}}
      - -X main.Minor={{.Minor}}
      - -X main.Patch={{.Patch}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64

archives:
  - id: archives
    builds:
      - binary
    format: "tar.gz"
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - docs/*
      - assets/*
      - static/*
      - templates/*
      - ./*/static/*
      - ./*/templates/*

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: orange-cloudfoundry
    name: cf-plugin-bg-restage
  prerelease: auto
  name_template: '{{.Tag}}'
